version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: reports_up_crop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  postgres_data:
    name: reports_up_crop_pg_data